dist: trusty
sudo: required

language: c++
compiler: gcc
os: linux

addons:
  sonarcloud:
    organization: "chakaponden-github"
  sonarqube:
    branches :
        - dev

install:
  - sudo apt-get install libgumbo-dev
  
script:
  - cmake .
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw_output make clean all
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
    