dist: trusty
sudo: required

language: c++
compiler: gcc
os: linux

env:
- SONARHOME=/tmp/sonarqube-6.6

addons:
  sonarqube:
    branches:
        - dev
  sonarcloud:
    organization: "chakaponden-github"
  apt:
      packages:
        - cmake
        - libtool
        - m4
        - autotools-dev
        - automake
        - pkg-config
        - libc6-dev
        - libglib2.0-dev
        - libsoup2.4-dev
        - libgtk2.0-dev

before_install:

install:
  - ./install-gumbo.sh

  ## install sonar server, run on 9001 port
  # - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.6.zip -P /tmp
  # - unzip -qq /tmp/sonarqube-6.6.zip -d /tmp
  # - rm -f /tmp/sonarqube-6.6.zip
  # - travis_retry wget -q https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.7/sonar-cxx-plugin-0.9.7.jar -P $SONARHOME/extensions/plugins
  # - echo "sonar.web.host=0.0.0.0" >> /tmp/sonarqube-6.6/conf/sonar.properties
  # - echo "sonar.web.port=9001" >> /tmp/sonarqube-6.6/conf/sonar.properties
  # - sudo $SONARHOME/bin/linux-x86-64/sonar.sh start
  # - sleep 60

  ## install sonar-scanner, run on 9001 port
  # - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip -P /tmp
  # - unzip -qq /tmp/sonar-scanner-cli-3.0.3.778-linux.zip -d /tmp
  # - rm -f /tmp/sonar-scanner-cli-3.0.3.778-linux.zip
  # - echo "sonar.host.url=http://localhost:9001" >> /tmp/sonar-scanner-3.0.3.778-linux/conf/sonar-scanner.properties

  ## install build-wrapper for sonar-scanner in sonar-scanner/bin dir
  # - travis_retry wget -q https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -P /tmp
  # - unzip -qq /tmp/build-wrapper-linux-x86.zip -d /tmp/sonar-scanner-3.0.3.778-linux/bin
  # - rm -f /tmp/build-wrapper-linux-x86.zip

script:
  #- export SONARQUBE_SKIPPED=false
  #- export SONAR_SCANNER_HOME=/tmp/sonar-scanner-3.0.3.778-linux

  - cmake .
  - build-wrapper-linux-x86-64 --out-dir bw_output make clean all
  # no licence for c++ sonar
  #- sonar-scanner

  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  #- /tmp/sonar-scanner-3.0.3.778-linux/bin/build-wrapper-linux-x86-64 --out-dir bw_output make clean all
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  #- sudo /tmp/sonar-scanner-3.0.3.778-linux/bin/sonar-scanner -X
  # - sudo $SONARHOME/bin/linux-x86-64/sonar.sh stop
  # - sudo rm -f /tmp/sonar-scanner-cli-3.0.3.778-linux -R
  # - sudo rm -f $SONARHOME -R
cache:
  directories:
    - '$HOME/.sonar/cache'