dist: trusty
sudo: required

language: c++
compiler: gcc
os: linux

env:
- SONARHOME=/tmp/sonarqube-6.6

addons:
  sonarcloud:
    organization: "chakaponden-github"
  apt:
      packages:
        - cmake
        - libtool
        - m4
        - autotools-dev
        - automake
        - pkg-config
        - libc6-dev
        - libglib2.0-dev
        - libsoup2.4-dev
        - libgtk2.0-dev
  sonarqube:
    branches :
        - dev

before_install:
  #- sudo apt-get -qq update
  # for build google gumbo
  #- sudo apt-get install -y -qq libtool m4 autotools-dev automake pkg-config libc6-dev
  # dependencies
  #- sudo apt-get install -y -qq libglib2.0-dev libsoup2.4-dev libgtk2.0-dev

install:
  - ./install-gumbo.sh

  - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.6.zip -P /tmp
  - unzip -qq /tmp/sonarqube-6.6.zip
  - travis_retry wget -q https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.7/sonar-cxx-plugin-0.9.7.jar -P $SONARQUBE_HOME/extensions/plugins
  - $SONARHOME/bin/linux-x86-64/sonar.sh start
  - which sonar.sh
  - which wrapper

script:
  # - LD_LIBRARY_PATH=$HOME/gumbo-parser/lib zef install .
  # - PERL6LIB=$PWD/blib/lib LD_LIBRARY_PATH=$HOME/gumbo-parser/lib prove -e perl6 -vr t/
  - cmake .
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw_output make clean all
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner
  - rm -f $SONARHOME -R
  - cat /home/travis/.sonarscanner/sonar-scanner-2.8/conf/sonar-scanner.properties
  - ls .?*
cache:
  directories:
    - '$HOME/.sonar/cache'
    