dist: trusty
sudo: required

language: c++
compiler: gcc
os: linux

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "gQQVH/0kTrG+95BO++XwtbuSJGc4Od004fuo4r379+ZBugB/feyagDh7GRtPjcctssdXDRChbx7bNGq3osH6HIRp3Jzozp/eCMVs5fgTj0/6HwmoRaZeDSnJke60rLTZ11J0bQSjlFY482n7SMIkcGjw2tvuLi46QkBq5TM0FKwPTDjb2OJmWApFLj7JzyijNHEBvTuiMAerlE3/g60nAZbgTcCBMqy7YQ4ZL8NOsXmq80WlgqrArT35JSPJboi8e+UKH1zvMgQPdmBSM8OREAXjZw9icVpT1f8H4Jnt6D8I1DC906Ich73yPaicp2lv9nEUlXLg/H+o9Q4RdegJPQFS+rMwmHe8b/jqlO6BOb6L3NWp1l44q4+8cjatlHy9VF8kKJCf3KzIVjyzzedkXsnOuHKciePVBg+w+JF1gA7u3NFSsdXJYaKa1AteDpkXCCn8DX525jEZk9vnEqi8x26E+9doOcuy25cG4JoRBFyGyQvx9dLCPMzlOUBAH+eDUUcGdmdQj0AbdMmRoIo9k7t3fRkc6evecD1Yw3ABdmtjPr97FA/Q7M4JSLoYhYanGCySN/HiwvPuttfNiL+JCFXYeGSy7YG3NSAmWNfepEfBDwcSITwC9cZvzix2c6q+NbEZQtOw2GL4RlFx8UNBUB+oai1UZqlHjaun2gtNgiI="

branches:
  only:
    - dev
addons:
  sonarcloud:
    organization: "chakaponden-github"
    branches:
      - dev
  apt:
      packages:
        - cmake
        - libtool
        - m4
        - autotools-dev
        - automake
        - pkg-config
        - libc6-dev
        - libglib2.0-dev
        - libsoup2.4-dev
        - libgtk2.0-dev
  coverity_scan:
    project:
      name: "chakaponden/itransition-task"
      description: "Build submitted via Travis CI"
    notification_email: ivangovnov07@gmail.com
    build_command_prepend: "make clean"
    build_command:   "build-wrapper-linux-x86-64 --out-dir bw_output make clean all"
    branch_pattern: coverity_scan

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - ./install-gumbo.sh

script:
  - export SONARQUBE_SKIPPED=false
  - cmake .
  - build-wrapper-linux-x86-64 --out-dir bw_output make clean all
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'