dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "chakaponden-github"
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'