dist: trusty
sudo: required

language: c++
compiler: gcc
os: linux

addons:
  sonarcloud:
    organization: "chakaponden-github"
  sonarqube:
    branches :
        - dev

install:
  #- sudo apt-get install libgumbo-dev
  # - git clone https://github.com/google/gumbo-parser.git
  # - echo $PWD
  # - ( cd gumbo-parser && ./autogen.sh && ./configure --prefix=$HOME/gumbo-parser && make install-exec )
  # - rm -rf gumbo-parser
  # - echo $PWD
  # - rakudobrew build-zef
  # - zef --/test --depsonly install .

script:
  # - LD_LIBRARY_PATH=$HOME/gumbo-parser/lib zef install .
  # - PERL6LIB=$PWD/blib/lib LD_LIBRARY_PATH=$HOME/gumbo-parser/lib prove -e perl6 -vr t/
  - cmake .
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw_output make clean all
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration

  - echo $SONARQUBE_HOME
  - sonar-scanner -v
  - echo $SONARQUBE_HOME
  - travis_retry wget -q https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.7/sonar-cxx-plugin-0.9.7.jar -P $SONARQUBE_HOME/extensions/plugins
  - echo $SONARQUBE_HOME
  
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
    